;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        c-electric-backspace
        c-electric-colon
        c-electric-delete-forward
        c-electric-lt-gt
        c-electric-semi&comma
        capitalize-dispatch
        delete-indentation
        double-quote-word
        downcase-dispatch
        eval-dispatch
        fixup-whitespace
        forward-sexp
        indent-for-tab-command
        join-following-line
        kill-region
        org-backward-sentence
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-forward-sentence
        org-kill-line
        org-return-indent
        org-self-insert-command
        org-yank
        python-indent-dedent-line-backspace
        smart-beginning-of-line
        sp--self-insert-command
        sp-remove-active-pair-overlay
        sp-self-insert-command
        sp-wrap-cancel
        upcase-dispatch
        wrap-region-trigger
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        edebug-next-mode
        end-of-buffer
        find-tag
        ido-find-file
        ido-switch-buffer
        ignore
        keyboard-escape-quit
        mc/dwim
        mc/mark-all-dispatch
        universal-argument-minus
        wdired-finish-edit
        ))
