;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-backspace
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        double-quote-word
        kill-region
        org-cycle
        org-force-self-insert
        org-kill-line
        org-return-indent
        org-yank
        smart-beginning-of-line
        wrap-region-trigger
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        mc/dwim
        wdired-finish-edit
        ))
