;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-backspace
        c-electric-colon
        c-electric-delete-forward
        c-electric-semi&comma
        double-quote-word
        fixup-whitespace
        kill-region
        org-backward-sentence
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-forward-sentence
        org-kill-line
        org-return-indent
        org-self-insert-command
        org-yank
        python-indent-dedent-line-backspace
        smart-beginning-of-line
        wrap-region-trigger
        ))

(setq mc/cmds-to-run-once
      '(
        end-of-buffer
        find-tag
        ido-find-file
        ido-switch-buffer
        ignore
        mc/dwim
        universal-argument-minus
        wdired-finish-edit
        ))
