* Отдельные методички
** Шпаргалка
** Как поставить dmd
- dired (открыть директорию в ido) - должен быть в самом начале!
- M-&
- пишем программу - комментарии, M-q
- компилируем
- создаем репозиторий, смотрим в магит
- выкладываем на гитхаб
- Таги
** Пишем презентацию в орг-моде (в маркдауне)
** Ссылки на конфиг

- Google, Lingvo, C-c C-o
- Выполнение лиспа
- Редактирование под рутом
- remote-term
- проверка правописания

** Разное
- контекстное авто-дополнение
- починить нумерованый список
- ввод Unicode символов
- re-builder
- M-;
- M-g g
- C-x C-q
- C-o, M-j
- Парные скобочки, удаление
- M-p, M-n
- M-c, M-u, M-l
- C-x C-o, M-\
- hexl-mode
- M-|
- registers
- редактирование в диред
- grep, wgrep
- calc
- rectangular regions
- Дополнительные курсоры
  В начале данного обзора я выразил мысль, что редактирование текста - давно
  решенная задача. Однако даже в, казалось бы, самых понятных областях нет-нет, да
  и произойдет какое-нибудь открытие. Одним из относительно недавних примеров
  такого открытия является идея использования /дополнительных курсоров/ для
  одновременного редактирования текста сразу в нескольких местах. Т.е. в буфере
  создаются, например, три курсора и последующие команды выполняются для каждого
  из них: жмем =C-b= - все три курсора сдвигаются влево, жмем =M-d= - удаляются 3
  слова - справа от каждого курсора.

  Трудно сказать, кто был её первооткрывателем и когда она впервые была
  реализована. Но более или менее широкое распространение она получила около 2010
  года. Такая запоздалая адаптация, наверное, связана с тем, что идея кажется
  слишком уж экзотической. Плюс, функциональность дополнительных курсоров во
  многом перекрывается с функциональностью клавиатурных макросов, интерактивной
  замены и /прямоугольных регионов/ (которые я ещё не затрагивал в рамках данного
  обзора).

  Признаться, мне и самому поначалу казалось, что ничего хорошего из неё
  получиться не может. Но прошло совсем немного времени и теперь я с трудом
  представляю, как без неё можно обходиться.

  Начнем знакомство с дополнительными курсорами на простом примере.
