* Введение

В этом репозитории находится моя конфигурация редактора [[https://www.gnu.org/software/emacs/][Emacs]].

Редактор Emacs - это главный инструмет моей профессиональной
деятельности, которая в первую очередь включает в себя разработку
программного обеспечения и всё, что с этим связано, а именно -
исследование, администрирование, тестирование, отладка, написание
документации и т.п.

* Установка

Для установки Emacs и его конфигурации, пользователи Ubuntu могут
воспользоваться следующей командой:

#+BEGIN_SRC sh
  wget https://raw.github.com/snosov1/bash/master/setup-ubuntu.bash -O /tmp/setup-ubuntu.bash && bash /tmp/setup-ubuntu.bash
#+END_SRC

Во время её выполнения устанавливается сам Emacs, клонируется этот
репозиторий и в домашнюю директорию добавляются символьные ссылки на
файлы из репозитория.

Пользователи других ОС могут проделать эти шаги в ручную. Вместо
создания символьных ссылок, файлы можно просто скопировать в домашнюю
директорию.

Для запуска нужно в терминале выполнить команду =emacs=, либо
воспользоваться любым другим способом, предоставляемым операционной
системой.

* Что такое C-, M- и всё остальное.
** обязательно перебиндить капс-лок
** обязательно слепая печать
** обязательно переключать на шифт-шифт

* Как отредактировать файл
** dired (картинки)
** ido
** C-x C-s
** переключение языка
** перемещение (C-a, C-e, M->, M-<, C-M-n, C-M-p, M-g g)
** посимвольные операции
** пословные операции (subword)
** M-p, M-n
** M-c, M-u, M-l
** C-o, M-j
** выделение региона (С-x h)
** kill/yank, kill-ring
** Парные скобочки, удаление
** C-=
** C-s, C-r, M-s o
** C-v, M-v, C-l
** Контекстное авто-дополнение

* Работа с окошками
* Как поставить dmd
** M-&
** пишем программу - комментарии, M-q
** компилируем
** создаем репозиторий, смотрим в магит
** выкладываем на гитхаб
** Таги
* Пишем презентацию в орг-моде, в маркдауне (починить)
* Разное
** пользование документацией
** M-|
** grep, wgrep
** редактирование в диред
** клавиатурные макросы
** несколько курсоров (rectangular regions)
** remote-term
** проверка правописания
** Выполнение лиспа
** Google, Lingvo
